<?php

/**
 * @file
 * Mbtiles for Openlayers module.
 */


/**
 * Implements hook_ctools_plugin_directory().
 */
function mbtiles_for_openlayers_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_type().
 */
function mbtiles_for_openlayers_ctools_plugin_type() {
  // For backwards compatibility, we allow for the use
  // of hooks to define these plugins.
  //
  // This should be removed in 7.x-3.x
  return array(
    'layer_types' => array(
      'use hooks' => TRUE,
      'classes' => array('layer_types'),
    )
  );
}
